config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :home do
    post 'auto_job', on: :collection
    get 'line_items', on: :member
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contract.rb
class Contract < ApplicationRecord

  has_many :renting_phases
  has_many :invoices

  validates_presence_of :user_name, message: '必须填写名字信息'
  validates_presence_of :begin_date, message: '必须选择开始日期'
  validates_presence_of :end_date, message: '必须选择结束日期'
  validates :cycle, presence: { message: '必须填写交付周期' }
  validates :amount_month, presence: { message: '必须填写每月租金' }


  validate :end_time_be_greater_than_begin_time


  before_create do
    renting_phases = RentingPhase.create_infos_and_return_amount self
    self.amount_count = renting_phases.map(&:amount_count).sum
    self.renting_phases = renting_phases
  end

  PRICE_UNIT = 1_000

  def end_time_be_greater_than_begin_time
    return if begin_date.nil? || end_date.nil?

    errors.add(:end_time, '结束日期必须大于开始日期') if begin_date > end_date
  end

  def price=(price)
    return if price.blank?

    self.amount_month = (price.to_f * PRICE_UNIT).to_i
  end


end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :contract
  belongs_to :renting_phase
  has_many :line_items

  # @param [Class<RentingPhase>] renting_phase
  def self.get_invoice_by_renting_phase(renting_phase)
    contract = renting_phase.contract
    invoice = Invoice.new begin_date: renting_phase.begin_date,
                          end_date: renting_phase.end_date,
                          pay_date: renting_phase.pay_date,
                          amount_count: renting_phase.amount_count
    invoice.contract = contract
    invoice.line_items = LineItem.get_line_items_by_invoice invoice, contract.amount_month
    invoice
  end


end

app/models/job.rb
# Job 方便综合的定时任务，简化了定时部分的内容如队列优先等
class Job
  class << self
    # date - 3天前的生成日期，默认定时任务传入,
    # @param [Class<Date>] date
    def generate_invoice(date)
      rps = RentingPhase.where(pay_date: date.to_date..date.to_date.next_day(3),
                               invoice_status: RentingPhase::NOT)
      rps.each do |rp|
        invoice = Invoice.get_invoice_by_renting_phase rp
        rp.invoice = invoice
        rp.invoice_status = RentingPhase::YES
        rp.save
      end
    end
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :invoice


  DATE_TYPE = [DAYS = 0, MONTH = 1].freeze

  # @param [Class<Invoice>] invoice
  def self.get_line_items_by_invoice(invoice, amount_month)
    _begin_date = invoice.begin_date
    line_items = []
    begin
      _end_date = _begin_date.end_of_month
      _end_date = invoice.end_date if _end_date > invoice.end_date
      line_items.push new_line_item_by_invoice(_begin_date,
                                               _end_date,
                                               amount_month)
      _begin_date = _begin_date.next_month.beginning_of_month
    end while _end_date != invoice.end_date
    line_items
  end

  def self.new_line_item_by_invoice(begin_date, end_date, amount_month)
    line_item = LineItem.new begin_date: begin_date,
                             end_date: end_date
    line_item.data_update(amount_month)
    line_item
  end

  def data_update(amount_month)
    self.date_type = is_month_type? ? MONTH : DAYS
    self.amount_count = self.unit_price = amount_month if is_month?
    if is_days?
      self.unit_price = (amount_month * 12 / 365).round(-1)
      # 这里不考虑小数后3位后的精度
      self.amount_count = (end_date.day - begin_date.day + 1) * unit_price
    end
  end

  private

  def is_month_type?
    begin_date.day == 1 && end_date.day == end_date.end_of_month.day
  end

  def is_days?
    self.date_type == DAYS
  end

  def is_month?
    self.date_type == MONTH
  end

end

app/models/public_method.rb
class PublicMethod
  class << self
    def month_pay(_begin_date, _end_date, month_money)
      if _begin_date.day == 1 && _end_date.day == _end_date.end_of_month.day
        month_money.round(-1)
      else
        days_money(_end_date.day - _begin_date.day + 1, month_money).round(-1)
      end
    end

    def days_money(days, month_money)
      month_money * 12 / 365.00 * days
    end
  end
end

app/models/renting_phase.rb
class RentingPhase < ApplicationRecord
  belongs_to :contract
  has_one :invoice

  INVOICE_STATUS = [NOT = 0, YES = 1].freeze
  
  # @param [Class<Contract>] cot
  def self.create_infos_and_return_amount(cot)
    new_renting_phases cot
  end

  def self.all_save(renting_phases = [])
    RentingPhase.transaction do
      renting_phases.each(&:save!)
    end
  end

  # @param [Class<Contract>] cot
  def self.new_renting_phases(cot)
    renting_phases = []
    index = 0
    start_date = pay_date = cot.begin_date
    begin
      renting_phases.push(new_renting_phase(start_date, index, cot, pay_date))
      start_date = renting_phases[index].end_date.next_month.beginning_of_month
      pay_date = renting_phases[index].next_pay_date
      index += 1
    end while renting_phases[index - 1].end_date < cot.end_date
    renting_phases
  end

  def self.new_renting_phase(_start_date, _index, _cot, _pay_date)
    renting_phase = RentingPhase.new begin_date: _start_date,
                                     contract_index: _index,
                                     contract: _cot,
                                     invoice_status: NOT
    renting_phase.set_end_date _start_date, _cot.cycle, _cot.end_date
    renting_phase.calculate_pay _cot.amount_month
    renting_phase.pay_date = _pay_date
    renting_phase
  end

  def calculate_pay(month_money)
    self.amount_count = 0
    _end_date = _begin_date = begin_date
    begin
      _end_date = _begin_date.end_of_month
      _end_date = end_date if _end_date > end_date
      self.amount_count += ::PublicMethod.month_pay(_begin_date, _end_date, month_money)
      _begin_date = _begin_date.next_month.beginning_of_month
    end while _end_date != end_date
  end

  def next_pay_date
    Date.new end_date.year, end_date.month, 15
  end

  def set_end_date(_start_date, cycle, over_date)
    self.end_date = _start_date.next_month(cycle - 1).end_of_month
    min_end_date over_date
  end

  private
  def min_end_date(other_end_date)
    self.end_date = other_end_date if end_date > other_end_date
  end

  def months(date)
    date.year * 12 + date.month
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @contracts = Contract.all
    @invoices = Invoice.all
  end

  def new
    @contract = Contract.new
  end

  def show
    @renting_phases = Contract.find(params[:id]).renting_phases.order(:contract_index)
  end

  def line_items
    @line_items = Invoice.find(params[:id]).line_items
  end

  def auto_job
    if params[:select_date].present?
      Job.generate_invoice Date.parse(params[:select_date])
    end
    redirect_to home_index_path
  end

  def create
    @contract = Contract.new(contract_params)
    return render :new unless @contract.save

    redirect_to home_index_path
  end

  private


  def contract_params
    params.require(:contract).permit(:user_name, :price, :begin_date, :end_date, :cycle)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def format_price(org_price)
    org_price / 1.00 / Contract::PRICE_UNIT
  end
end

app/views/home/index.html.erb
<h1>Demo</h1>
<%= link_to '创建', new_home_path %>

<% if @contracts.any? %>
  <h1>合同信息</h1>
  <table>
    <thead>
    <tr>
      <th>开始日期</th>
      <th>结束日期</th>
      <th>每月租金</th>
      <th>交租周期</th>
      <th>总租金</th>
      <th>操作</th>
    </tr>
    </thead>
    <tbody>
      <% @contracts.each do |obj| %>
      <tr>
        <td><%= obj.begin_date %></td>
        <td><%= obj.end_date %></td>
        <td><%= format_price obj.amount_month %></td>
        <td><%= obj.cycle %></td>
        <td><%= format_price obj.amount_count %></td>
        <td>
          <%= link_to "明细", home_path(obj) %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<br />
<%= form_with url: auto_job_home_index_path, local: true , class: 'table' do |f|%>
  <div class="line" style="width: 400px">
   选择日期（用于生成报告）: <%= f.date_field :select_date %><%= f.submit '生成' %>
  </div>
<% end %>
<% if @invoices.any? %>
  <h1>以生成的账单</h1>
  <table>
    <thead>
    <tr>
      <th>开始日期</th>
      <th>结束日期</th>
      <th>交租日期</th>
      <th>总租金</th>
      <th>操作</th>
    </tr>
    </thead>
    <tbody>
    <% @invoices.each do |obj| %>
      <tr>
        <td><%= obj.begin_date %></td>
        <td><%= obj.end_date %></td>
        <td><%= obj.pay_date %></td>
        <td><%= format_price obj.amount_count %></td>
        <td>
          <%= link_to "明细", line_items_home_path(obj) %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/home/line_items.html.erb
<h1>账单明细</h1>
<table>
  <thead>
  <tr>
    <th>开始日期</th>
    <th>结束日期</th>
    <th>日期类型</th>
    <th>单价</th>
    <th>总价</th>
  </tr>
  </thead>
  <tbody>
  <% @line_items.each do |obj| %>
    <tr>
      <td><%= obj.begin_date %></td>
      <td><%= obj.end_date %></td>
      <td><%= obj.date_type == LineItem::DAYS ? '日' : '月' %></td>
      <td><%= format_price obj.unit_price %></td>
      <td><%= format_price obj.amount_count %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/home/new.html.erb
<h1>合同创建</h1>

<% if @contract.errors.any? %>
  <div id="error_explanation">
    <h2><%= "提交有如下 #{@contract.errors.count} 处错误" %></h2>

    <ul>
      <% @contract.errors.each do |attr| %>
        <li><%= @contract.errors[attr][0] %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with url: home_index_path, model: @contract, local: true , class: 'table' do |f|%>
  <div class="line">
    用户名: <%= f.text_field :user_name %>
  </div>
  <div class="line">
    开始日期: <%= f.date_field :begin_date %>
  </div>
  <div class="line">
    结束日期: <%= f.date_field :end_date %>
  </div>
  <div class="line">
    每月租金（元）: <%= f.number_field :price, min: 0.01, step: 0.01 %>
  </div>
  <div class="line">
    交租周期（月）: <%= f.number_field :cycle, min: 1, max: 12, step: 1 %>
  </div>
  <div class="line">
    <%= f.submit '确认提交' %>
  </div>
<% end %>

app/views/home/show.html.erb
<h1>交租阶段信息</h1>
<table>
  <thead>
  <tr>
    <th>交租阶段开始结束日期</th>
    <th>交租日</th>
    <th>交租阶段总租金</th>
    <th>是否生成账单</th>
  </tr>
  </thead>
  <tbody>
  <% @renting_phases.each do |obj| %>
    <tr>
      <td><%= "#{obj.begin_date} ～ #{obj.end_date}" %></td>
      <td><%= obj.pay_date %></td>
      <td><%= format_price obj.amount_count %></td>
      <td><%= obj.invoice_status == RentingPhase::YES ? '是' : '否' %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KuyiTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>